version: "3"
services:
  flask:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: mobile-order
    container_name: mobile-order
    volumes:
      - ..:/usr/src/app
    command: flask run --host=0.0.0.0
