version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: app
    volumes:
      - ../app:/usr/src/app
    command: flask run --host=0.0.0.0
